# Generated by Django 4.0 on 2022-02-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField(blank=True, null=True)),
                ('profile_avatar', models.ImageField(blank=True, null=True, upload_to='profile_avatar/')),
                ('profile_bg', models.ImageField(blank=True, null=True, upload_to='profile_bg/')),
                ('profile_description', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_activity', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
