# Generated by Django 4.0 on 2022-02-08 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('site_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_ID', models.CharField(max_length=10)),
            ],
            managers=[
                ('objects_id', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_profile.profileid'),
        ),
    ]
