# Generated by Django 4.0 on 2022-02-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profile', '0002_profileid_alter_profile_profile_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profileid',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='test_id',
            field=models.SlugField(blank=True, max_length=10, null=True),
        ),
    ]
