# Generated by Django 4.0 on 2022-02-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profile', '0003_alter_profileid_managers_profile_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileid',
            name='prof_ID',
            field=models.SlugField(max_length=10),
        ),
    ]
