# Generated by Django 4.0 on 2022-02-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profile', '0004_alter_profileid_prof_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_slug_url',
            field=models.SlugField(default='none', max_length=10),
        ),
    ]
