# Generated by Django 4.0 on 2022-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profile', '0007_alter_profileid_profile_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
