# Generated by Django 4.0 on 2022-02-13 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_profile', '0009_rename_follow_followmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
                ('folder_bg', models.ImageField(blank=True, null=True, upload_to='folder_bg/')),
                ('folder_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_profile.profile')),
            ],
        ),
    ]
