# Generated by Django 4.0 on 2022-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_profile', '0012_folder_folder_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_url',
            field=models.SlugField(default='folder_u', max_length=100),
        ),
    ]
